<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-23 03:48:29.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\Exam
 *
 * @ORM\Entity()
 * @ORM\Table(name="exam", indexes={@ORM\Index(name="fk_exam_teacher1_idx", columns={"teacher_id"})})
 */
class Exam implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 作業名稱
     *
     * @ORM\Column(type="string", length=200)
     */
    protected $subject;

    /**
     * 建立時間
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $create_time;

    /**
     * 開始上傳時間
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $open_time;

    /**
     * 結束時間
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $close_time;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    protected $memo;

    /**
     * @ORM\Column(type="integer")
     */
    protected $teacher_id;

    /**
     * @ORM\OneToMany(targetEntity="ExamDatum", mappedBy="exam")
     * @ORM\JoinColumn(name="id", referencedColumnName="exam_id", nullable=false)
     */
    protected $examData;

    /**
     * @ORM\ManyToOne(targetEntity="Teacher", inversedBy="exams")
     * @ORM\JoinColumn(name="teacher_id", referencedColumnName="id", nullable=false)
     */
    protected $teacher;

    public function __construct()
    {
        $this->examData = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\Exam
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of subject.
     *
     * @param string $subject
     * @return \Base\Entity\Exam
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get the value of subject.
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Set the value of create_time.
     *
     * @param \DateTime $create_time
     * @return \Base\Entity\Exam
     */
    public function setCreateTime($create_time)
    {
        $this->create_time = $create_time;

        return $this;
    }

    /**
     * Get the value of create_time.
     *
     * @return \DateTime
     */
    public function getCreateTime()
    {
        return $this->create_time;
    }

    /**
     * Set the value of open_time.
     *
     * @param \DateTime $open_time
     * @return \Base\Entity\Exam
     */
    public function setOpenTime($open_time)
    {
        $this->open_time = $open_time;

        return $this;
    }

    /**
     * Get the value of open_time.
     *
     * @return \DateTime
     */
    public function getOpenTime()
    {
        return $this->open_time;
    }

    /**
     * Set the value of close_time.
     *
     * @param \DateTime $close_time
     * @return \Base\Entity\Exam
     */
    public function setCloseTime($close_time)
    {
        $this->close_time = $close_time;

        return $this;
    }

    /**
     * Get the value of close_time.
     *
     * @return \DateTime
     */
    public function getCloseTime()
    {
        return $this->close_time;
    }

    /**
     * Set the value of memo.
     *
     * @param string $memo
     * @return \Base\Entity\Exam
     */
    public function setMemo($memo)
    {
        $this->memo = $memo;

        return $this;
    }

    /**
     * Get the value of memo.
     *
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     * Set the value of teacher_id.
     *
     * @param integer $teacher_id
     * @return \Base\Entity\Exam
     */
    public function setTeacherId($teacher_id)
    {
        $this->teacher_id = $teacher_id;

        return $this;
    }

    /**
     * Get the value of teacher_id.
     *
     * @return integer
     */
    public function getTeacherId()
    {
        return $this->teacher_id;
    }

    /**
     * Add ExamDatum entity to collection (one to many).
     *
     * @param \Base\Entity\ExamDatum $examDatum
     * @return \Base\Entity\Exam
     */
    public function addExamDatum(ExamDatum $examDatum)
    {
        $this->examData[] = $examDatum;

        return $this;
    }

    /**
     * Remove ExamDatum entity from collection (one to many).
     *
     * @param \Base\Entity\ExamDatum $examDatum
     * @return \Base\Entity\Exam
     */
    public function removeExamDatum(ExamDatum $examDatum)
    {
        $this->examData->removeElement($examDatum);

        return $this;
    }

    /**
     * Get ExamDatum entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getExamData()
    {
        return $this->examData;
    }

    /**
     * Set Teacher entity (many to one).
     *
     * @param \Base\Entity\Teacher $teacher
     * @return \Base\Entity\Exam
     */
    public function setTeacher(Teacher $teacher = null)
    {
        $this->teacher = $teacher;

        return $this;
    }

    /**
     * Get Teacher entity (many to one).
     *
     * @return \Base\Entity\Teacher
     */
    public function getTeacher()
    {
        return $this->teacher;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'subject',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'create_time',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'open_time',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'close_time',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'memo',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'teacher_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'subject', 'create_time', 'open_time', 'close_time', 'memo', 'teacher_id');
        $relationFields = array('teacher');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'subject', 'create_time', 'open_time', 'close_time', 'memo', 'teacher_id');
    }
}