<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-20 12:32:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\SchoolOffice
 *
 * 處室
 *
 * @ORM\Entity
 * @ORM\Table(name="school_office")
 */
class SchoolOffice implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 單位名稱
     *
     * @ORM\Column(name="`name`", type="string", length=45)
     */
    protected $name;

    /**
     * 排序
     *
     * @ORM\Column(name="`rank`", type="integer", nullable=true)
     */
    protected $rank;

    /**
     * 單位電話
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $office_phone;

    /**
     * 分機
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $office_phone_ext;

    /**
     * 網址
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $office_url;

    /**
     * @ORM\OneToMany(targetEntity="TeacherTitle", mappedBy="schoolOffice")
     * @ORM\JoinColumn(name="id", referencedColumnName="school_office_id", nullable=false)
     */
    protected $teacherTitles;

    public function __construct()
    {
        $this->teacherTitles = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\SchoolOffice
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Base\Entity\SchoolOffice
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of rank.
     *
     * @param integer $rank
     * @return \Base\Entity\SchoolOffice
     */
    public function setRank($rank)
    {
        $this->rank = $rank;

        return $this;
    }

    /**
     * Get the value of rank.
     *
     * @return integer
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Set the value of office_phone.
     *
     * @param string $office_phone
     * @return \Base\Entity\SchoolOffice
     */
    public function setOfficePhone($office_phone)
    {
        $this->office_phone = $office_phone;

        return $this;
    }

    /**
     * Get the value of office_phone.
     *
     * @return string
     */
    public function getOfficePhone()
    {
        return $this->office_phone;
    }

    /**
     * Set the value of office_phone_ext.
     *
     * @param string $office_phone_ext
     * @return \Base\Entity\SchoolOffice
     */
    public function setOfficePhoneExt($office_phone_ext)
    {
        $this->office_phone_ext = $office_phone_ext;

        return $this;
    }

    /**
     * Get the value of office_phone_ext.
     *
     * @return string
     */
    public function getOfficePhoneExt()
    {
        return $this->office_phone_ext;
    }

    /**
     * Set the value of office_url.
     *
     * @param string $office_url
     * @return \Base\Entity\SchoolOffice
     */
    public function setOfficeUrl($office_url)
    {
        $this->office_url = $office_url;

        return $this;
    }

    /**
     * Get the value of office_url.
     *
     * @return string
     */
    public function getOfficeUrl()
    {
        return $this->office_url;
    }

    /**
     * Add TeacherTitle entity to collection (one to many).
     *
     * @param \Base\Entity\TeacherTitle $teacherTitle
     * @return \Base\Entity\SchoolOffice
     */
    public function addTeacherTitle(TeacherTitle $teacherTitle)
    {
        $this->teacherTitles[] = $teacherTitle;

        return $this;
    }

    /**
     * Remove TeacherTitle entity from collection (one to many).
     *
     * @param \Base\Entity\TeacherTitle $teacherTitle
     * @return \Base\Entity\SchoolOffice
     */
    public function removeTeacherTitle(TeacherTitle $teacherTitle)
    {
        $this->teacherTitles->removeElement($teacherTitle);

        return $this;
    }

    /**
     * Get TeacherTitle entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTeacherTitles()
    {
        return $this->teacherTitles;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'name',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'rank',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'office_phone',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'office_phone_ext',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'office_url',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'name', 'rank', 'office_phone', 'office_phone_ext', 'office_url');
        $relationFields = array();
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'name', 'rank', 'office_phone', 'office_phone_ext', 'office_url');
    }
}