<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-20 12:32:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\Semester
 *
 * 學期
 *
 * @ORM\Entity(repositoryClass="SemesterRepository")
 * @ORM\Table(name="semester")
 */
class Semester implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 學年度
     *
     * @ORM\Column(name="`year`", type="integer")
     */
    protected $year;

    /**
     * 學期
     *
     * @ORM\Column(type="integer")
     */
    protected $semester;

    /**
     * 學期開始日
     *
     * @ORM\Column(type="date", nullable=true)
     */
    protected $begin_date;

    /**
     * 學期結束日
     *
     * @ORM\Column(type="date", nullable=true)
     */
    protected $end_date;

    /**
     * 更新時間
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $update_time;

    /**
     * 開學日
     *
     * @ORM\Column(type="date", nullable=true)
     */
    protected $semester_start_date;

    /**
     * 結業日
     *
     * @ORM\Column(type="date", nullable=true)
     */
    protected $semester_end_date;

    /**
     * @ORM\OneToMany(targetEntity="SemesterClass", mappedBy="semester")
     * @ORM\JoinColumn(name="id", referencedColumnName="semester_id", nullable=false)
     */
    protected $semesterClasses;

    /**
     * @ORM\OneToMany(targetEntity="SemesterTeacher", mappedBy="semester")
     * @ORM\JoinColumn(name="id", referencedColumnName="semester_id", nullable=false)
     */
    protected $semesterTeachers;

    public function __construct()
    {
        $this->semesterClasses = new ArrayCollection();
        $this->semesterTeachers = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\Semester
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of year.
     *
     * @param integer $year
     * @return \Base\Entity\Semester
     */
    public function setYear($year)
    {
        $this->year = $year;

        return $this;
    }

    /**
     * Get the value of year.
     *
     * @return integer
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * Set the value of semester.
     *
     * @param integer $semester
     * @return \Base\Entity\Semester
     */
    public function setSemester($semester)
    {
        $this->semester = $semester;

        return $this;
    }

    /**
     * Get the value of semester.
     *
     * @return integer
     */
    public function getSemester()
    {
        return $this->semester;
    }

    /**
     * Set the value of begin_date.
     *
     * @param \DateTime $begin_date
     * @return \Base\Entity\Semester
     */
    public function setBeginDate($begin_date)
    {
        $this->begin_date = $begin_date;

        return $this;
    }

    /**
     * Get the value of begin_date.
     *
     * @return \DateTime
     */
    public function getBeginDate()
    {
        return $this->begin_date;
    }

    /**
     * Set the value of end_date.
     *
     * @param \DateTime $end_date
     * @return \Base\Entity\Semester
     */
    public function setEndDate($end_date)
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * Get the value of end_date.
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->end_date;
    }

    /**
     * Set the value of update_time.
     *
     * @param \DateTime $update_time
     * @return \Base\Entity\Semester
     */
    public function setUpdateTime($update_time)
    {
        $this->update_time = $update_time;

        return $this;
    }

    /**
     * Get the value of update_time.
     *
     * @return \DateTime
     */
    public function getUpdateTime()
    {
        return $this->update_time;
    }

    /**
     * Set the value of semester_start_date.
     *
     * @param \DateTime $semester_start_date
     * @return \Base\Entity\Semester
     */
    public function setSemesterStartDate($semester_start_date)
    {
        $this->semester_start_date = $semester_start_date;

        return $this;
    }

    /**
     * Get the value of semester_start_date.
     *
     * @return \DateTime
     */
    public function getSemesterStartDate()
    {
        return $this->semester_start_date;
    }

    /**
     * Set the value of semester_end_date.
     *
     * @param \DateTime $semester_end_date
     * @return \Base\Entity\Semester
     */
    public function setSemesterEndDate($semester_end_date)
    {
        $this->semester_end_date = $semester_end_date;

        return $this;
    }

    /**
     * Get the value of semester_end_date.
     *
     * @return \DateTime
     */
    public function getSemesterEndDate()
    {
        return $this->semester_end_date;
    }

    /**
     * Add SemesterClass entity to collection (one to many).
     *
     * @param \Base\Entity\SemesterClass $semesterClass
     * @return \Base\Entity\Semester
     */
    public function addSemesterClass(SemesterClass $semesterClass)
    {
        $this->semesterClasses[] = $semesterClass;

        return $this;
    }

    /**
     * Remove SemesterClass entity from collection (one to many).
     *
     * @param \Base\Entity\SemesterClass $semesterClass
     * @return \Base\Entity\Semester
     */
    public function removeSemesterClass(SemesterClass $semesterClass)
    {
        $this->semesterClasses->removeElement($semesterClass);

        return $this;
    }

    /**
     * Get SemesterClass entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSemesterClasses()
    {
        return $this->semesterClasses;
    }

    /**
     * Add SemesterTeacher entity to collection (one to many).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\Semester
     */
    public function addSemesterTeacher(SemesterTeacher $semesterTeacher)
    {
        $this->semesterTeachers[] = $semesterTeacher;

        return $this;
    }

    /**
     * Remove SemesterTeacher entity from collection (one to many).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\Semester
     */
    public function removeSemesterTeacher(SemesterTeacher $semesterTeacher)
    {
        $this->semesterTeachers->removeElement($semesterTeacher);

        return $this;
    }

    /**
     * Get SemesterTeacher entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSemesterTeachers()
    {
        return $this->semesterTeachers;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'year',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'semester',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'begin_date',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'end_date',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'update_time',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'semester_start_date',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'semester_end_date',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'year', 'semester', 'begin_date', 'end_date', 'update_time', 'semester_start_date', 'semester_end_date');
        $relationFields = array();
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'year', 'semester', 'begin_date', 'end_date', 'update_time', 'semester_start_date', 'semester_end_date');
    }
}