<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-20 12:32:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\SemesterTeacher
 *
 * @ORM\Entity(repositoryClass="SemesterTeacherRepository")
 * @ORM\Table(name="semester_teacher", indexes={@ORM\Index(name="fk_semester_teacher_semester1_idx", columns={"semester_id"}), @ORM\Index(name="fk_semester_teacher_teacher1_idx", columns={"teacher_id"}), @ORM\Index(name="fk_semester_teacher_teacher_title1_idx", columns={"teacher_title_id"})})
 */
class SemesterTeacher implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $semester_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $teacher_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $teacher_title_id;

    /**
     * @ORM\OneToMany(targetEntity="TeacherCourse", mappedBy="semesterTeacher")
     * @ORM\JoinColumn(name="id", referencedColumnName="semester_teacher_id", nullable=false)
     */
    protected $teacherCourses;

    /**
     * @ORM\ManyToOne(targetEntity="Semester", inversedBy="semesterTeachers")
     * @ORM\JoinColumn(name="semester_id", referencedColumnName="id", nullable=false)
     */
    protected $semester;

    /**
     * @ORM\ManyToOne(targetEntity="Teacher", inversedBy="semesterTeachers")
     * @ORM\JoinColumn(name="teacher_id", referencedColumnName="id", nullable=false)
     */
    protected $teacher;

    /**
     * @ORM\ManyToOne(targetEntity="TeacherTitle", inversedBy="semesterTeachers")
     * @ORM\JoinColumn(name="teacher_title_id", referencedColumnName="id", nullable=false)
     */
    protected $teacherTitle;

    public function __construct()
    {
        $this->teacherCourses = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\SemesterTeacher
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of semester_id.
     *
     * @param integer $semester_id
     * @return \Base\Entity\SemesterTeacher
     */
    public function setSemesterId($semester_id)
    {
        $this->semester_id = $semester_id;

        return $this;
    }

    /**
     * Get the value of semester_id.
     *
     * @return integer
     */
    public function getSemesterId()
    {
        return $this->semester_id;
    }

    /**
     * Set the value of teacher_id.
     *
     * @param integer $teacher_id
     * @return \Base\Entity\SemesterTeacher
     */
    public function setTeacherId($teacher_id)
    {
        $this->teacher_id = $teacher_id;

        return $this;
    }

    /**
     * Get the value of teacher_id.
     *
     * @return integer
     */
    public function getTeacherId()
    {
        return $this->teacher_id;
    }

    /**
     * Set the value of teacher_title_id.
     *
     * @param integer $teacher_title_id
     * @return \Base\Entity\SemesterTeacher
     */
    public function setTeacherTitleId($teacher_title_id)
    {
        $this->teacher_title_id = $teacher_title_id;

        return $this;
    }

    /**
     * Get the value of teacher_title_id.
     *
     * @return integer
     */
    public function getTeacherTitleId()
    {
        return $this->teacher_title_id;
    }

    /**
     * Add TeacherCourse entity to collection (one to many).
     *
     * @param \Base\Entity\TeacherCourse $teacherCourse
     * @return \Base\Entity\SemesterTeacher
     */
    public function addTeacherCourse(TeacherCourse $teacherCourse)
    {
        $this->teacherCourses[] = $teacherCourse;

        return $this;
    }

    /**
     * Remove TeacherCourse entity from collection (one to many).
     *
     * @param \Base\Entity\TeacherCourse $teacherCourse
     * @return \Base\Entity\SemesterTeacher
     */
    public function removeTeacherCourse(TeacherCourse $teacherCourse)
    {
        $this->teacherCourses->removeElement($teacherCourse);

        return $this;
    }

    /**
     * Get TeacherCourse entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTeacherCourses()
    {
        return $this->teacherCourses;
    }

    /**
     * Set Semester entity (many to one).
     *
     * @param \Base\Entity\Semester $semester
     * @return \Base\Entity\SemesterTeacher
     */
    public function setSemester(Semester $semester = null)
    {
        $this->semester = $semester;

        return $this;
    }

    /**
     * Get Semester entity (many to one).
     *
     * @return \Base\Entity\Semester
     */
    public function getSemester()
    {
        return $this->semester;
    }

    /**
     * Set Teacher entity (many to one).
     *
     * @param \Base\Entity\Teacher $teacher
     * @return \Base\Entity\SemesterTeacher
     */
    public function setTeacher(Teacher $teacher = null)
    {
        $this->teacher = $teacher;

        return $this;
    }

    /**
     * Get Teacher entity (many to one).
     *
     * @return \Base\Entity\Teacher
     */
    public function getTeacher()
    {
        return $this->teacher;
    }

    /**
     * Set TeacherTitle entity (many to one).
     *
     * @param \Base\Entity\TeacherTitle $teacherTitle
     * @return \Base\Entity\SemesterTeacher
     */
    public function setTeacherTitle(TeacherTitle $teacherTitle = null)
    {
        $this->teacherTitle = $teacherTitle;

        return $this;
    }

    /**
     * Get TeacherTitle entity (many to one).
     *
     * @return \Base\Entity\TeacherTitle
     */
    public function getTeacherTitle()
    {
        return $this->teacherTitle;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'semester_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'teacher_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'teacher_title_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'semester_id', 'teacher_id', 'teacher_title_id');
        $relationFields = array('semester', 'teacher', 'teacherTitle');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'semester_id', 'teacher_id', 'teacher_title_id');
    }
}