<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-20 12:32:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\TeacherCourse
 *
 * 教師任課資料
 *
 * @ORM\Entity(repositoryClass="TeacherCourseRepository")
 * @ORM\Table(name="teacher_course", indexes={@ORM\Index(name="fk_teacher_course_semester_teacher1_idx", columns={"semester_teacher_id"}), @ORM\Index(name="fk_teacher_course_semester_class1_idx", columns={"semester_class_id"})})
 */
class TeacherCourse implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 科目
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $subject_name;

    /**
     * 節數
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $section_number;

    /**
     * @ORM\Column(type="integer")
     */
    protected $semester_teacher_id;

    /**
     * @ORM\Column(type="integer")
     */
    protected $semester_class_id;

    /**
     * @ORM\ManyToOne(targetEntity="SemesterTeacher", inversedBy="teacherCourses")
     * @ORM\JoinColumn(name="semester_teacher_id", referencedColumnName="id", nullable=false)
     */
    protected $semesterTeacher;

    /**
     * @ORM\ManyToOne(targetEntity="SemesterClass", inversedBy="teacherCourses")
     * @ORM\JoinColumn(name="semester_class_id", referencedColumnName="id", nullable=false)
     */
    protected $semesterClass;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\TeacherCourse
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of subject_name.
     *
     * @param string $subject_name
     * @return \Base\Entity\TeacherCourse
     */
    public function setSubjectName($subject_name)
    {
        $this->subject_name = $subject_name;

        return $this;
    }

    /**
     * Get the value of subject_name.
     *
     * @return string
     */
    public function getSubjectName()
    {
        return $this->subject_name;
    }

    /**
     * Set the value of section_number.
     *
     * @param integer $section_number
     * @return \Base\Entity\TeacherCourse
     */
    public function setSectionNumber($section_number)
    {
        $this->section_number = $section_number;

        return $this;
    }

    /**
     * Get the value of section_number.
     *
     * @return integer
     */
    public function getSectionNumber()
    {
        return $this->section_number;
    }

    /**
     * Set the value of semester_teacher_id.
     *
     * @param integer $semester_teacher_id
     * @return \Base\Entity\TeacherCourse
     */
    public function setSemesterTeacherId($semester_teacher_id)
    {
        $this->semester_teacher_id = $semester_teacher_id;

        return $this;
    }

    /**
     * Get the value of semester_teacher_id.
     *
     * @return integer
     */
    public function getSemesterTeacherId()
    {
        return $this->semester_teacher_id;
    }

    /**
     * Set the value of semester_class_id.
     *
     * @param integer $semester_class_id
     * @return \Base\Entity\TeacherCourse
     */
    public function setSemesterClassId($semester_class_id)
    {
        $this->semester_class_id = $semester_class_id;

        return $this;
    }

    /**
     * Get the value of semester_class_id.
     *
     * @return integer
     */
    public function getSemesterClassId()
    {
        return $this->semester_class_id;
    }

    /**
     * Set SemesterTeacher entity (many to one).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\TeacherCourse
     */
    public function setSemesterTeacher(SemesterTeacher $semesterTeacher = null)
    {
        $this->semesterTeacher = $semesterTeacher;

        return $this;
    }

    /**
     * Get SemesterTeacher entity (many to one).
     *
     * @return \Base\Entity\SemesterTeacher
     */
    public function getSemesterTeacher()
    {
        return $this->semesterTeacher;
    }

    /**
     * Set SemesterClass entity (many to one).
     *
     * @param \Base\Entity\SemesterClass $semesterClass
     * @return \Base\Entity\TeacherCourse
     */
    public function setSemesterClass(SemesterClass $semesterClass = null)
    {
        $this->semesterClass = $semesterClass;

        return $this;
    }

    /**
     * Get SemesterClass entity (many to one).
     *
     * @return \Base\Entity\SemesterClass
     */
    public function getSemesterClass()
    {
        return $this->semesterClass;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'subject_name',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'section_number',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'semester_teacher_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'semester_class_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'subject_name', 'section_number', 'semester_teacher_id', 'semester_class_id');
        $relationFields = array('semesterTeacher', 'semesterClass');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'subject_name', 'section_number', 'semester_teacher_id', 'semester_class_id');
    }
}