<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-20 12:32:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\TeacherTitle
 *
 * @ORM\Entity(repositoryClass="TeacherTitleRepository")
 * @ORM\Table(name="teacher_title", indexes={@ORM\Index(name="fk_teacher_title_school_office1_idx", columns={"school_office_id"})})
 */
class TeacherTitle implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="`name`", type="string", length=45, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(type="integer")
     */
    protected $school_office_id;

    /**
     * 職別
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $title_kind;

    /**
     * 排序
     *
     * @ORM\Column(name="`rank`", type="integer", nullable=true)
     */
    protected $rank;

    /**
     * @ORM\OneToMany(targetEntity="SemesterTeacher", mappedBy="teacherTitle")
     * @ORM\JoinColumn(name="id", referencedColumnName="teacher_title_id", nullable=false)
     */
    protected $semesterTeachers;

    /**
     * @ORM\ManyToOne(targetEntity="SchoolOffice", inversedBy="teacherTitles")
     * @ORM\JoinColumn(name="school_office_id", referencedColumnName="id", nullable=false)
     */
    protected $schoolOffice;

    public function __construct()
    {
        $this->semesterTeachers = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\TeacherTitle
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Base\Entity\TeacherTitle
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of school_office_id.
     *
     * @param integer $school_office_id
     * @return \Base\Entity\TeacherTitle
     */
    public function setSchoolOfficeId($school_office_id)
    {
        $this->school_office_id = $school_office_id;

        return $this;
    }

    /**
     * Get the value of school_office_id.
     *
     * @return integer
     */
    public function getSchoolOfficeId()
    {
        return $this->school_office_id;
    }

    /**
     * Set the value of title_kind.
     *
     * @param string $title_kind
     * @return \Base\Entity\TeacherTitle
     */
    public function setTitleKind($title_kind)
    {
        $this->title_kind = $title_kind;

        return $this;
    }

    /**
     * Get the value of title_kind.
     *
     * @return string
     */
    public function getTitleKind()
    {
        return $this->title_kind;
    }

    /**
     * Set the value of rank.
     *
     * @param integer $rank
     * @return \Base\Entity\TeacherTitle
     */
    public function setRank($rank)
    {
        $this->rank = $rank;

        return $this;
    }

    /**
     * Get the value of rank.
     *
     * @return integer
     */
    public function getRank()
    {
        return $this->rank;
    }

    /**
     * Add SemesterTeacher entity to collection (one to many).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\TeacherTitle
     */
    public function addSemesterTeacher(SemesterTeacher $semesterTeacher)
    {
        $this->semesterTeachers[] = $semesterTeacher;

        return $this;
    }

    /**
     * Remove SemesterTeacher entity from collection (one to many).
     *
     * @param \Base\Entity\SemesterTeacher $semesterTeacher
     * @return \Base\Entity\TeacherTitle
     */
    public function removeSemesterTeacher(SemesterTeacher $semesterTeacher)
    {
        $this->semesterTeachers->removeElement($semesterTeacher);

        return $this;
    }

    /**
     * Get SemesterTeacher entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSemesterTeachers()
    {
        return $this->semesterTeachers;
    }

    /**
     * Set SchoolOffice entity (many to one).
     *
     * @param \Base\Entity\SchoolOffice $schoolOffice
     * @return \Base\Entity\TeacherTitle
     */
    public function setSchoolOffice(SchoolOffice $schoolOffice = null)
    {
        $this->schoolOffice = $schoolOffice;

        return $this;
    }

    /**
     * Get SchoolOffice entity (many to one).
     *
     * @return \Base\Entity\SchoolOffice
     */
    public function getSchoolOffice()
    {
        return $this->schoolOffice;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     * 
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'name',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'school_office_id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'title_kind',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'rank',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     * 
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'name', 'school_office_id', 'title_kind', 'rank');
        $relationFields = array('schoolOffice');
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'name', 'school_office_id', 'title_kind', 'rank');
    }
}