<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.3 (doctrine2-zf2inputfilterannotation) on 2019-01-20 12:32:01.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace Base\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Zend\InputFilter\InputFilter;
use Zend\InputFilter\Factory as InputFactory;
use Zend\InputFilter\InputFilterAwareInterface;
use Zend\InputFilter\InputFilterInterface;

/**
 * Base\Entity\User
 *
 * 使用者
 *
 * @ORM\Entity(repositoryClass="UserRepository")
 * @ORM\Table(name="`user`")
 */
class User implements InputFilterAwareInterface
{
    /**
     * Instance of InputFilterInterface.
     *
     * @var InputFilter
     */
    private $inputFilter;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * 使用者帳號
     *
     * @ORM\Column(type="string", length=100)
     */
    protected $username;

    /**
     * 使用者權限
     *
     * @ORM\Column(name="`level`", type="integer", nullable=true)
     */
    protected $level;

    /**
     * 姓名
     *
     * @ORM\Column(name="`name`", type="string", length=50)
     */
    protected $name;

    /**
     * 職稱
     *
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    protected $job_title;

    /**
     * 密碼
     *
     * @ORM\Column(name="`password`", type="string", length=128, nullable=true)
     */
    protected $password;

    /**
     * 單位代號
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $mr_unit_id;

    /**
     * 電子郵件
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $email;

    /**
     * 電話
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $phone;

    /**
     * 手機
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $mobile;

    /**
     * 顯示名稱
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $display_name;

    /**
     * 角色
     *
     * @ORM\Column(name="`role`", type="string", length=45, nullable=true)
     */
    protected $role;

    /**
     * 分機
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $phone_ext;

    /**
     * 是否在職
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $is_active;

    /**
     * email 驗證
     *
     * @ORM\Column(type="string", length=45, nullable=true)
     */
    protected $mail_verify;

    /**
     * 遠端登入username
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    protected $remote_username;

    /**
     * @ORM\OneToMany(targetEntity="Menu", mappedBy="user")
     * @ORM\JoinColumn(name="id", referencedColumnName="user_id", nullable=false)
     */
    protected $menus;

    /**
     * @ORM\OneToMany(targetEntity="Page", mappedBy="user")
     * @ORM\JoinColumn(name="id", referencedColumnName="user_id", nullable=false)
     */
    protected $pages;

    /**
     * @ORM\OneToMany(targetEntity="Student", mappedBy="user")
     * @ORM\JoinColumn(name="id", referencedColumnName="user_id", nullable=false)
     */
    protected $students;

    /**
     * @ORM\OneToMany(targetEntity="Teacher", mappedBy="user")
     * @ORM\JoinColumn(name="id", referencedColumnName="user_id", nullable=false)
     */
    protected $teachers;

    /**
     * @ORM\ManyToMany(targetEntity="Role", inversedBy="users")
     * @ORM\JoinTable(name="user_has_role",
     *     joinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)},
     *     inverseJoinColumns={@ORM\JoinColumn(name="role_id", referencedColumnName="id", nullable=false)}
     * )
     */
    protected $roles;

    public function __construct()
    {
        $this->menus = new ArrayCollection();
        $this->pages = new ArrayCollection();
        $this->students = new ArrayCollection();
        $this->teachers = new ArrayCollection();
        $this->roles = new ArrayCollection();
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \Base\Entity\User
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of username.
     *
     * @param string $username
     * @return \Base\Entity\User
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get the value of username.
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set the value of level.
     *
     * @param integer $level
     * @return \Base\Entity\User
     */
    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    /**
     * Get the value of level.
     *
     * @return integer
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Set the value of name.
     *
     * @param string $name
     * @return \Base\Entity\User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get the value of name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of job_title.
     *
     * @param string $job_title
     * @return \Base\Entity\User
     */
    public function setJobTitle($job_title)
    {
        $this->job_title = $job_title;

        return $this;
    }

    /**
     * Get the value of job_title.
     *
     * @return string
     */
    public function getJobTitle()
    {
        return $this->job_title;
    }

    /**
     * Set the value of password.
     *
     * @param string $password
     * @return \Base\Entity\User
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get the value of password.
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set the value of mr_unit_id.
     *
     * @param integer $mr_unit_id
     * @return \Base\Entity\User
     */
    public function setMrUnitId($mr_unit_id)
    {
        $this->mr_unit_id = $mr_unit_id;

        return $this;
    }

    /**
     * Get the value of mr_unit_id.
     *
     * @return integer
     */
    public function getMrUnitId()
    {
        return $this->mr_unit_id;
    }

    /**
     * Set the value of email.
     *
     * @param string $email
     * @return \Base\Entity\User
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get the value of email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set the value of phone.
     *
     * @param string $phone
     * @return \Base\Entity\User
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get the value of phone.
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set the value of mobile.
     *
     * @param string $mobile
     * @return \Base\Entity\User
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;

        return $this;
    }

    /**
     * Get the value of mobile.
     *
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Set the value of display_name.
     *
     * @param string $display_name
     * @return \Base\Entity\User
     */
    public function setDisplayName($display_name)
    {
        $this->display_name = $display_name;

        return $this;
    }

    /**
     * Get the value of display_name.
     *
     * @return string
     */
    public function getDisplayName()
    {
        return $this->display_name;
    }

    /**
     * Set the value of role.
     *
     * @param string $role
     * @return \Base\Entity\User
     */
    public function setRole($role)
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Get the value of role.
     *
     * @return string
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Set the value of phone_ext.
     *
     * @param string $phone_ext
     * @return \Base\Entity\User
     */
    public function setPhoneExt($phone_ext)
    {
        $this->phone_ext = $phone_ext;

        return $this;
    }

    /**
     * Get the value of phone_ext.
     *
     * @return string
     */
    public function getPhoneExt()
    {
        return $this->phone_ext;
    }

    /**
     * Set the value of is_active.
     *
     * @param integer $is_active
     * @return \Base\Entity\User
     */
    public function setIsActive($is_active)
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * Get the value of is_active.
     *
     * @return integer
     */
    public function getIsActive()
    {
        return $this->is_active;
    }

    /**
     * Set the value of mail_verify.
     *
     * @param string $mail_verify
     * @return \Base\Entity\User
     */
    public function setMailVerify($mail_verify)
    {
        $this->mail_verify = $mail_verify;

        return $this;
    }

    /**
     * Get the value of mail_verify.
     *
     * @return string
     */
    public function getMailVerify()
    {
        return $this->mail_verify;
    }

    /**
     * Set the value of remote_username.
     *
     * @param string $remote_username
     * @return \Base\Entity\User
     */
    public function setRemoteUsername($remote_username)
    {
        $this->remote_username = $remote_username;

        return $this;
    }

    /**
     * Get the value of remote_username.
     *
     * @return string
     */
    public function getRemoteUsername()
    {
        return $this->remote_username;
    }

    /**
     * Add Menu entity to collection (one to many).
     *
     * @param \Base\Entity\Menu $menu
     * @return \Base\Entity\User
     */
    public function addMenu(Menu $menu)
    {
        $this->menus[] = $menu;

        return $this;
    }

    /**
     * Remove Menu entity from collection (one to many).
     *
     * @param \Base\Entity\Menu $menu
     * @return \Base\Entity\User
     */
    public function removeMenu(Menu $menu)
    {
        $this->menus->removeElement($menu);

        return $this;
    }

    /**
     * Get Menu entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMenus()
    {
        return $this->menus;
    }

    /**
     * Add Page entity to collection (one to many).
     *
     * @param \Base\Entity\Page $page
     * @return \Base\Entity\User
     */
    public function addPage(Page $page)
    {
        $this->pages[] = $page;

        return $this;
    }

    /**
     * Remove Page entity from collection (one to many).
     *
     * @param \Base\Entity\Page $page
     * @return \Base\Entity\User
     */
    public function removePage(Page $page)
    {
        $this->pages->removeElement($page);

        return $this;
    }

    /**
     * Get Page entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPages()
    {
        return $this->pages;
    }

    /**
     * Add Student entity to collection (one to many).
     *
     * @param \Base\Entity\Student $student
     * @return \Base\Entity\User
     */
    public function addStudent(Student $student)
    {
        $this->students[] = $student;

        return $this;
    }

    /**
     * Remove Student entity from collection (one to many).
     *
     * @param \Base\Entity\Student $student
     * @return \Base\Entity\User
     */
    public function removeStudent(Student $student)
    {
        $this->students->removeElement($student);

        return $this;
    }

    /**
     * Get Student entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStudents()
    {
        return $this->students;
    }

    /**
     * Add Teacher entity to collection (one to many).
     *
     * @param \Base\Entity\Teacher $teacher
     * @return \Base\Entity\User
     */
    public function addTeacher(Teacher $teacher)
    {
        $this->teachers[] = $teacher;

        return $this;
    }

    /**
     * Remove Teacher entity from collection (one to many).
     *
     * @param \Base\Entity\Teacher $teacher
     * @return \Base\Entity\User
     */
    public function removeTeacher(Teacher $teacher)
    {
        $this->teachers->removeElement($teacher);

        return $this;
    }

    /**
     * Get Teacher entity collection (one to many).
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTeachers()
    {
        return $this->teachers;
    }

    /**
     * Add Role entity to collection.
     *
     * @param \Base\Entity\Role $role
     * @return \Base\Entity\User
     */
    public function addRole(Role $role)
    {
        $role->addUser($this);
        $this->roles[] = $role;

        return $this;
    }

    /**
     * Remove Role entity from collection.
     *
     * @param \Base\Entity\Role $role
     * @return \Base\Entity\User
     */
    public function removeRole(Role $role)
    {
        $role->removeUser($this);
        $this->roles->removeElement($role);

        return $this;
    }

    /**
     * Get Role entity collection.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Not used, Only defined to be compatible with InputFilterAwareInterface.
     *
     * @param \Zend\InputFilter\InputFilterInterface $inputFilter
     * @throws \Exception
     */
    public function setInputFilter(InputFilterInterface $inputFilter)
    {
        throw new \Exception("Not used.");
    }

    /**
     * Return a for this entity configured input filter instance.
     *
     * @return InputFilterInterface
     */
    public function getInputFilter()
    {
        if ($this->inputFilter instanceof InputFilterInterface) {
            return $this->inputFilter;
        }
        $factory = new InputFactory();
        $filters = array(
            array(
                'name' => 'id',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'username',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'level',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'name',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'job_title',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'password',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'mr_unit_id',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'email',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'phone',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'mobile',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'display_name',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'role',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'phone_ext',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'is_active',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'mail_verify',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
            array(
                'name' => 'remote_username',
                'required' => false,
                'filters' => array(),
                'validators' => array(),
            ),
        );
        $this->inputFilter = $factory->createInputFilter($filters);

        return $this->inputFilter;
    }

    /**
     * Populate entity with the given data.
     * The set* method will be used to set the data.
     *
     * @param array $data
     * @return boolean
     */
    public function populate(array $data = array())
    {
        foreach ($data as $field => $value) {
            $setter = sprintf('set%s', ucfirst(
                str_replace(' ', '', ucwords(str_replace('_', ' ', $field)))
            ));
            if (method_exists($this, $setter)) {
                $this->{$setter}($value);
            }
        }

        return true;
    }

    /**
     * Return a array with all fields and data.
     * Default the relations will be ignored.
     *
     * @param array $fields
     * @return array
     */
    public function getArrayCopy(array $fields = array())
    {
        $dataFields = array('id', 'username', 'level', 'name', 'job_title', 'password', 'mr_unit_id', 'email', 'phone', 'mobile', 'display_name', 'role', 'phone_ext', 'is_active', 'mail_verify', 'remote_username');
        $relationFields = array();
        $copiedFields = array();
        foreach ($relationFields as $relationField) {
            $map = null;
            if (array_key_exists($relationField, $fields)) {
                $map = $fields[$relationField];
                $fields[] = $relationField;
                unset($fields[$relationField]);
            }
            if (!in_array($relationField, $fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $relationField)))));
            $relationEntity = $this->{$getter}();
            $copiedFields[$relationField] = (!is_null($map))
                ? $relationEntity->getArrayCopy($map)
                : $relationEntity->getArrayCopy();
            $fields = array_diff($fields, array($relationField));
        }
        foreach ($dataFields as $dataField) {
            if (!in_array($dataField, $fields) && !empty($fields)) {
                continue;
            }
            $getter = sprintf('get%s', ucfirst(str_replace(' ', '', ucwords(str_replace('_', ' ', $dataField)))));
            $copiedFields[$dataField] = $this->{$getter}();
        }

        return $copiedFields;
    }

    public function __sleep()
    {
        return array('id', 'username', 'level', 'name', 'job_title', 'password', 'mr_unit_id', 'email', 'phone', 'mobile', 'display_name', 'role', 'phone_ext', 'is_active', 'mail_verify', 'remote_username');
    }

    public static function hashPassword($player, $password)
    {
        return ($player->getPassword() === md5($password));
    }

}
