<?php $form = $this->form;
// $form->setAttribute('action',
// 		$this->url('Application', array(
// 				'controller'=>'user','action' => 'form'
// 				)));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('name'));
// echo $this->formRow($form->get('subject'));
echo $this->formRow($form->get('email'));
echo $this->formRow($form->get('captcha'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>
