<p>
	親愛的用戶
	<?php echo $this->user->getUsername()?>
</p>
<p>您從 [] 重新設定您的密碼，若要完成設定，請點選以下連結:</p>
<p>

	<a
		href="<?php echo $this->url; ?>/user/reset-password/<?php echo $this->user->getCheckCode()?>">重設我的密碼</a>
</p>
<p>
	或連至
	<?php echo $this->url ?>
	/user/reset-password/
	<?php echo $this->user->getCheckCode()?>
</p>
<p>謝謝您，希望您使用[]愉快！</p>
<p>若有任何問題，請聯絡</p>

<p>敬上</p>

************************************** 本信件由系統自動產生，請勿回覆此信件。

**************************************
