<?php 
$displayOptions = array(
        //The class attribute added to the form tag
        //'class'                 => 'my-form-class',
        'elements'              => array(
                'username'			=> array(
                        'class'		=>	'input-large',
                        'required'	=>	true,
                ),
                'email'			=> array(
                        'class'		=>	'input-large',
                        'required'	=>	true,
                ),
                'submit'	=> array(
                        'class' => 'btn btn-primary'
                )

        ),
);
//Form object
$form           = $this->form;
$formType       = $this->formType;
$validData      = $this->validData;

$form->prepare();
?>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<!--Sidebar content-->
		</div>
		<div class="span10">
			<!--Body content-->
			<h1>忘記密碼查詢</h1>
			<?php if(count($this->flashMessages)) : ?>
			<div class="alert alert-error">
				<button class="close" data-dismiss="alert" type="button">×</button>
				<ul>
					<?php foreach ($this->flashMessages as $msg) : ?>
					<li><?php echo $msg; ?></li>
					<?php endforeach; ?>
				</ul>
			</div>
			<?php endif?>
			<div class="box-content">
				<?php echo $this->formTwb($form, $formType, $displayOptions);?>
			</div>
		</div>
	</div>
</div>
