
<?php 
$displayOptions = array(
        //The class attribute added to the form tag
        //'class'                 => 'my-form-class',
        'elements'              => array(
                'password'			=> array(
                        'class'		=>	'input-large',
                        'required'	=>	true,
                ),
                're_password'			=> array(
                        'class'		=>	'input-large',
                        'required'	=>	true,
                ),
                'submit'	=> array(
                        'class' => 'btn btn-primary'
                )

        ),
);
$form           = $this->form;
$formType       = $this->formType;
$validData      = $this->validData;

$form->prepare();
?>

<div class="container-fluid">
	<div class="row-fluid">
		<div class="span2">
			<!--Sidebar content-->
		</div>
		<div class="span10">
			<h2>您好，你可以在下方輸入您的新密碼，我們會立即為您重新設定密碼！</h2>
			<div class="box-content">
				<?php echo $this->formTwb($form, $formType, $displayOptions);?>
			</div>
		</div>
	</div>
</div>

